# Makefile
#
# Canonical development and automation entry points for mktext.
# Maintainers edit src/mktext.bash.  make build generates the supported dist/
# artifact flavors with immutable version and source-revision metadata.

SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c

SRC_DIR := src
DIST_DIR := dist
SOURCE_LIBRARY := $(SRC_DIR)/mktext.bash
DEV_LIBRARY := $(DIST_DIR)/mktext.dev.bash
DIST_LIBRARY := $(DIST_DIR)/mktext.bash
MIN_LIBRARY := $(DIST_DIR)/mktext.min.bash
DEV_CHECKSUM := $(DEV_LIBRARY).sha256
DIST_CHECKSUM := $(DIST_LIBRARY).sha256
MIN_CHECKSUM := $(MIN_LIBRARY).sha256

TESTS_DIR := tests
TEST_SCRIPTS := $(TESTS_DIR)/mktext.bats
BUILD_DEPENDENCY_TEST := $(TESTS_DIR)/build-dependencies.bats
COMPAT_TEST := $(TESTS_DIR)/compat-bash.bash
SHELL_SCRIPTS := $(SOURCE_LIBRARY) $(COMPAT_TEST)

VENDOR_DIR := vendor
DEPENDENCY_MANIFEST := dependencies.txt
BASHDEPS := $(VENDOR_DIR)/bashdeps.bash
BASHDEPS_VERSION := 0.0.6
BASHDEPS_URL := https://github.com/wesley-dean/bashdeps/releases/download/v$(BASHDEPS_VERSION)/bashdeps.bash
BASHDEPS_SHA256 := bb6c807fa12c010950bda06172ac0611d278c57aca1f8352f41502d0d76b4e6c
BASH_MINIFIER := $(VENDOR_DIR)/bash-minifier.bash
DOXYGEN_BASH_FILTER := $(VENDOR_DIR)/doxygen-bash.awk
REFERENCE_DOC_DIR := doc/reference

VERSION ?= 0.0.0-dev
BUILD_COMMIT ?= $(shell git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')

.PHONY: all build check clean deps deps-check docs docs-clean FORCE format test test-build test-generated test-source verify-bashdeps

##
# Synchronize external build/development dependencies, then build all release
# artifacts.  The recursive invocation keeps ordering explicit under parallel Make.
#
all: deps
	$(MAKE) --no-print-directory build

##
# Generate the development, comment-stripped, and minified distribution artifacts
# with identical immutable build metadata, then write one SHA-256 check file for
# each artifact.
#
# This target is deliberately network-free.  It consumes the already-prepared
# Bash-Minifier dependency and fails clearly when that build input is absent.
#
build: $(SOURCE_LIBRARY)
	@test -f "$(BASH_MINIFIER)" && test ! -L "$(BASH_MINIFIER)" || { \
		printf '%s\n' 'Missing build dependency vendor/bash-minifier.bash; run make deps or make all' >&2; \
		exit 1; \
	}
	mkdir -p "$(DIST_DIR)"
	{ \
		printf '%s\n' '#!/usr/bin/env bash'; \
		printf '\n'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Maintained source: src/mktext.bash'; \
		printf '\n'; \
		printf '__mktext_version=%q\n' "$(VERSION)"; \
		printf '__mktext_build_date=%q\n' "$(BUILD_DATE)"; \
		printf '__mktext_build_commit=%q\n' "$(BUILD_COMMIT)"; \
		printf '\n'; \
		cat "$(SOURCE_LIBRARY)"; \
		printf '\n'; \
		printf '%s\n' 'if [[ $${BASH_SOURCE[0]} == "$$0" ]]; then'; \
		printf '%s\n' '  case $${0##*/} in'; \
		printf '%s\n' '    mktext.dev.bash | mktext.min.bash)'; \
		printf '%s\n' '      if mktext "$$@"; then'; \
		printf '%s\n' '        exit 0'; \
		printf '%s\n' '      else'; \
		printf '%s\n' '        exit $$?'; \
		printf '%s\n' '      fi'; \
		printf '%s\n' '      ;;'; \
		printf '%s\n' '  esac'; \
		printf '%s\n' 'fi'; \
	} >"$(DEV_LIBRARY).tmp"
	chmod 0755 "$(DEV_LIBRARY).tmp"
	mv "$(DEV_LIBRARY).tmp" "$(DEV_LIBRARY)"
	{ \
		printf '%s\n' '#!/usr/bin/env bash'; \
		printf '\n'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Maintained source: src/mktext.bash'; \
		printf '\n'; \
		printf '__mktext_version=%q\n' "$(VERSION)"; \
		printf '__mktext_build_date=%q\n' "$(BUILD_DATE)"; \
		printf '__mktext_build_commit=%q\n' "$(BUILD_COMMIT)"; \
		printf '\n'; \
		cat "$(SOURCE_LIBRARY)" | sed '/^#/d'; \
		printf '\n'; \
		printf '%s\n' 'if [[ $${BASH_SOURCE[0]} == "$$0" ]]; then'; \
		printf '%s\n' '  case $${0##*/} in'; \
		printf '%s\n' '    mktext.dev.bash | mktext.min.bash)'; \
		printf '%s\n' '      if mktext "$$@"; then'; \
		printf '%s\n' '        exit 0'; \
		printf '%s\n' '      else'; \
		printf '%s\n' '        exit $$?'; \
		printf '%s\n' '      fi'; \
		printf '%s\n' '      ;;'; \
		printf '%s\n' '  esac'; \
		printf '%s\n' 'fi'; \
	} >"$(DIST_LIBRARY).tmp"
	chmod 0755 "$(DIST_LIBRARY).tmp"
	mv "$(DIST_LIBRARY).tmp" "$(DIST_LIBRARY)"
	bash "$(BASH_MINIFIER)" -F <"$(DIST_LIBRARY)" >"$(MIN_LIBRARY).tmp"
	chmod 0755 "$(MIN_LIBRARY).tmp"
	mv "$(MIN_LIBRARY).tmp" "$(MIN_LIBRARY)"
	@if command -v sha256sum >/dev/null 2>&1; then \
		cd "$(DIST_DIR)"; \
		sha256sum "$(notdir $(DEV_LIBRARY))" >"$(notdir $(DEV_CHECKSUM)).tmp"; \
		sha256sum "$(notdir $(DIST_LIBRARY))" >"$(notdir $(DIST_CHECKSUM)).tmp"; \
		sha256sum "$(notdir $(MIN_LIBRARY))" >"$(notdir $(MIN_CHECKSUM)).tmp"; \
	elif command -v shasum >/dev/null 2>&1; then \
		cd "$(DIST_DIR)"; \
		shasum -a 256 "$(notdir $(DEV_LIBRARY))" >"$(notdir $(DEV_CHECKSUM)).tmp"; \
		shasum -a 256 "$(notdir $(DIST_LIBRARY))" >"$(notdir $(DIST_CHECKSUM)).tmp"; \
		shasum -a 256 "$(notdir $(MIN_LIBRARY))" >"$(notdir $(MIN_CHECKSUM)).tmp"; \
	else \
		printf '%s\n' 'No SHA-256 command is available for build checksums' >&2; \
		exit 1; \
	fi
	mv "$(DEV_CHECKSUM).tmp" "$(DEV_CHECKSUM)"
	mv "$(DIST_CHECKSUM).tmp" "$(DIST_CHECKSUM)"
	mv "$(MIN_CHECKSUM).tmp" "$(MIN_CHECKSUM)"

##
# Validate hand-maintained Bash source with the shell parser and ShellCheck.
#
check:
	bash -n $(SHELL_SCRIPTS)
	shellcheck $(SHELL_SCRIPTS)

##
# Format hand-maintained Bash source using the repository's canonical formatter.
#
format:
	shfmt -w -i 2 -ci $(SHELL_SCRIPTS)

##
# Run source behavior, generated-artifact behavior, checksum, and dependency-boundary tests.
#
test: test-source test-build test-generated

##
# Run observable-behavior tests directly against maintained source.
#
test-source:
	MKTEXT_LIBRARY="$(SOURCE_LIBRARY)" \
		MKTEXT_EXPECT_VERSION='0.0.0-dev' \
		MKTEXT_EXPECT_BUILD_DATE='unknown' \
		MKTEXT_EXPECT_BUILD_COMMIT='unknown' \
		bats $(TEST_SCRIPTS)
	MKTEXT_LIBRARY="$(SOURCE_LIBRARY)" bash $(COMPAT_TEST)

##
# Build and run the same observable-behavior suite against all three generated flavors.
#
test-generated: build
	@for artifact in "$(DEV_LIBRARY)" "$(DIST_LIBRARY)" "$(MIN_LIBRARY)"; do \
		bash -n "$$artifact"; \
		test -x "$$artifact"; \
		test "$$(head -n 1 "$$artifact")" = '#!/usr/bin/env bash'; \
		MKTEXT_LIBRARY="$$artifact" \
			MKTEXT_EXPECT_VERSION="$(VERSION)" \
			MKTEXT_EXPECT_BUILD_DATE="$(BUILD_DATE)" \
			MKTEXT_EXPECT_BUILD_COMMIT="$(BUILD_COMMIT)" \
			bats $(TEST_SCRIPTS); \
		MKTEXT_LIBRARY="$$artifact" bash $(COMPAT_TEST); \
		"$$artifact" --version >/dev/null; \
	done
	grep -Fq '## @file src/mktext.bash' "$(DEV_LIBRARY)"
	! grep -Fq '## @file src/mktext.bash' "$(DIST_LIBRARY)"
	! grep -Fq '## @file src/mktext.bash' "$(MIN_LIBRARY)"
	grep -Fxq '# Generated by make build. Do not edit directly.' "$(DIST_LIBRARY)"
	test "$$(grep -c '^#' "$(DIST_LIBRARY)")" -eq 3
	cd "$(DIST_DIR)" && if command -v sha256sum >/dev/null 2>&1; then \
		sha256sum -c "$(notdir $(DEV_CHECKSUM))"; \
		sha256sum -c "$(notdir $(DIST_CHECKSUM))"; \
		sha256sum -c "$(notdir $(MIN_CHECKSUM))"; \
	else \
		shasum -a 256 -c "$(notdir $(DEV_CHECKSUM))"; \
		shasum -a 256 -c "$(notdir $(DIST_CHECKSUM))"; \
		shasum -a 256 -c "$(notdir $(MIN_CHECKSUM))"; \
	fi

##
# Exercise dependency bootstrap, synchronization, build isolation, and runtime isolation.
#
test-build:
	bats "$(BUILD_DEPENDENCY_TEST)"

##
# Force the bootstrap file target to validate cached bytes whenever requested.
#
FORCE:

##
# Bootstrap the pinned released bashdeps executable used to process dependencies.txt.
#
# Make directly owns only this bootstrap dependency.  Correct cached bytes avoid
# network access.  Missing or mismatched bytes are replaced only after a staged
# download matches the committed SHA-256 digest.
#
$(BASHDEPS): FORCE
	@mkdir -p "$(VENDOR_DIR)"
	@verify_hash() { \
		path=$$1; \
		if command -v sha256sum >/dev/null 2>&1; then \
			printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$$path" | sha256sum -c - >/dev/null 2>&1; \
		elif command -v shasum >/dev/null 2>&1; then \
			actual="$$(shasum -a 256 "$$path" | awk '{print $$1}')"; \
			[[ "$$actual" == "$(BASHDEPS_SHA256)" ]]; \
		else \
			return 2; \
		fi; \
	}; \
	if ! command -v sha256sum >/dev/null 2>&1 && ! command -v shasum >/dev/null 2>&1; then \
		printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; \
		exit 1; \
	fi; \
	if [[ -f "$@" && ! -L "$@" ]] && verify_hash "$@"; then \
		chmod 0755 "$@"; \
		exit 0; \
	fi; \
	if ! command -v curl >/dev/null 2>&1; then \
		printf '%s\n' 'curl is required to bootstrap bashdeps.bash' >&2; \
		exit 1; \
	fi; \
	tmp="$@.tmp"; \
	rm -f "$$tmp"; \
	trap 'rm -f "$$tmp"' EXIT; \
	curl -fsSL "$(BASHDEPS_URL)" -o "$$tmp"; \
	if ! verify_hash "$$tmp"; then \
		printf '%s\n' 'Downloaded bashdeps.bash does not match the committed SHA-256 digest' >&2; \
		exit 1; \
	fi; \
	chmod 0755 "$$tmp"; \
	mv "$$tmp" "$@"; \
	trap - EXIT

##
# Verify the already-present bashdeps bootstrap without network access or repair.
#
verify-bashdeps:
	@test -x "$(BASHDEPS)" && test ! -L "$(BASHDEPS)" || { \
		printf '%s\n' 'Missing, non-executable, or unsafe bashdeps bootstrap; run make deps' >&2; \
		exit 1; \
	}
	@if command -v sha256sum >/dev/null 2>&1; then \
		printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$(BASHDEPS)" | sha256sum -c - >/dev/null; \
	elif command -v shasum >/dev/null 2>&1; then \
		actual="$$(shasum -a 256 "$(BASHDEPS)" | awk '{print $$1}')"; \
		[[ "$$actual" == "$(BASHDEPS_SHA256)" ]]; \
	else \
		printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; \
		exit 1; \
	fi

##
# Synchronize manifest-managed build/development dependencies through bashdeps.
#
# This target may use the network.  It is the repair/convergence path used by all
# and docs, while plain build remains offline.
#
deps: $(BASHDEPS) $(DEPENDENCY_MANIFEST)
	$(MAKE) --no-print-directory verify-bashdeps
	"$(BASHDEPS)" sync "$(DEPENDENCY_MANIFEST)"

##
# Verify bootstrap and manifest-managed dependency state without network repair.
#
deps-check: verify-bashdeps $(DEPENDENCY_MANIFEST)
	"$(BASHDEPS)" verify "$(DEPENDENCY_MANIFEST)"

##
# Remove generated reference documentation completely.
#
docs-clean:
	rm -rf "$(REFERENCE_DOC_DIR)"

##
# Generate browsable Doxygen reference documentation.
#
# The Bash Doxygen filter is a manifest-managed data artifact.  This consumer
# target owns the executable mode Doxygen needs rather than asking bashdeps to
# infer artifact semantics.
#
docs: docs-clean deps
	chmod 0755 "$(DOXYGEN_BASH_FILTER)"
	mkdir -p "$(REFERENCE_DOC_DIR)"
	doxygen Doxyfile

clean: docs-clean
	rm -rf "$(DIST_DIR)" "$(VENDOR_DIR)"
