# Makefile
#
# Canonical development and automation entry points for mktext.
# Maintainers edit src/mktext.bash.  make build generates dist/mktext.bash with
# immutable version and source-revision metadata for consumers.

SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c

SRC_DIR := src
DIST_DIR := dist
SOURCE_LIBRARY := $(SRC_DIR)/mktext.bash
DIST_LIBRARY := $(DIST_DIR)/mktext.bash

TESTS_DIR := tests
TEST_SCRIPTS := $(TESTS_DIR)/*.bats
COMPAT_TEST := $(TESTS_DIR)/compat-bash.bash
SHELL_SCRIPTS := $(SOURCE_LIBRARY) $(COMPAT_TEST)

VENDOR_DIR := vendor
DOXYGEN_BASH_FILTER := $(VENDOR_DIR)/doxygen-bash.awk
DOXYGEN_BASH_FILTER_URL := https://raw.githubusercontent.com/wesley-dean/bash-doxygen/refs/heads/main/doxygen-bash.awk
REFERENCE_DOC_DIR := doc/reference

VERSION ?= 0.0.0-dev
BUILD_COMMIT ?= $(shell git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')

.PHONY: all build check clean docs docs-clean format test test-source test-dist

all: build

##
# Generate the sourceable and executable distribution artifact with immutable
# build metadata.
#
# This target is intentionally phony.  VERSION, BUILD_DATE, and BUILD_COMMIT are
# build inputs rather than filesystem prerequisites, so regenerating the tiny
# artifact on every invocation prevents stale development metadata from being
# reused by a later release build.
#
build: $(SOURCE_LIBRARY)
	mkdir -p "$(DIST_DIR)"
	{ \
		printf '%s\n' '#!/usr/bin/env bash'; \
		printf '\n'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Maintained source: src/mktext.bash'; \
		printf '\n'; \
		printf '__mktext_version=%q\n' "$(VERSION)"; \
		printf '__mktext_build_date=%q\n' "$(BUILD_DATE)"; \
		printf '__mktext_build_commit=%q\n' "$(BUILD_COMMIT)"; \
		printf '\n'; \
		cat "$(SOURCE_LIBRARY)" \
			| sed '/^#/d'; \
	} >"$(DIST_LIBRARY).tmp"
	chmod 0755 "$(DIST_LIBRARY).tmp"
	mv "$(DIST_LIBRARY).tmp" "$(DIST_LIBRARY)"

##
# Validate hand-maintained Bash source with the shell parser and ShellCheck.
#
check:
	bash -n $(SHELL_SCRIPTS)
	shellcheck $(SHELL_SCRIPTS)

##
# Format hand-maintained Bash source using the repository's canonical formatter.
#
format:
	shfmt -w -i 2 -ci $(SHELL_SCRIPTS)

##
# Run the behavior suite against maintained source and generated distribution.
#
test: test-source test-dist

##
# Run observable-behavior tests directly against maintained source.
#
test-source:
	MKTEXT_LIBRARY="$(SOURCE_LIBRARY)" \
		MKTEXT_EXPECT_VERSION='0.0.0-dev' \
		MKTEXT_EXPECT_BUILD_DATE='unknown' \
		MKTEXT_EXPECT_BUILD_COMMIT='unknown' \
		bats $(TEST_SCRIPTS)
	MKTEXT_LIBRARY="$(SOURCE_LIBRARY)" bash $(COMPAT_TEST)

##
# Build and run the same observable-behavior tests against the consumer artifact.
#
test-dist: build
	bash -n "$(DIST_LIBRARY)"
	test -x "$(DIST_LIBRARY)"
	test "$$(head -n 1 "$(DIST_LIBRARY)")" = '#!/usr/bin/env bash'
	grep -Fxq '# Generated by make build. Do not edit directly.' "$(DIST_LIBRARY)"
	grep -Fxq '# Maintained source: src/mktext.bash' "$(DIST_LIBRARY)"
	test "$$(grep -c '^#' "$(DIST_LIBRARY)")" -eq 3
	MKTEXT_LIBRARY="$(DIST_LIBRARY)" \
		MKTEXT_EXPECT_VERSION="$(VERSION)" \
		MKTEXT_EXPECT_BUILD_DATE="$(BUILD_DATE)" \
		MKTEXT_EXPECT_BUILD_COMMIT="$(BUILD_COMMIT)" \
		bats $(TEST_SCRIPTS)
	MKTEXT_LIBRARY="$(DIST_LIBRARY)" bash $(COMPAT_TEST)

##
# Download the Bash Doxygen filter used to preprocess shell source files.
#
$(DOXYGEN_BASH_FILTER):
	mkdir -p "$(VENDOR_DIR)"
	curl -fsSL "$(DOXYGEN_BASH_FILTER_URL)" -o "$@.tmp"
	chmod 0755 "$@.tmp"
	mv "$@.tmp" "$@"

##
# Remove generated reference documentation completely.
#
docs-clean:
	rm -rf "$(REFERENCE_DOC_DIR)"

##
# Generate browsable Doxygen reference documentation.
#
docs: docs-clean $(DOXYGEN_BASH_FILTER)
	mkdir -p "$(REFERENCE_DOC_DIR)"
	doxygen Doxyfile

clean: docs-clean
	rm -rf "$(DIST_DIR)"
	$(RM) -f "$(DOXYGEN_BASH_FILTER)"
	-rmdir "$(VENDOR_DIR)" >/dev/null 2>&1
